#!/bin/bash -e

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

main() {
    cd "$root"

    [[ -d node_modules ]] || npm i
    [[ -d tunes ]] || ./scripts/download-music-pack

    compile
}

compile() {
    echo -e '\n;\n' > crlf
    rm -fr dist
    mkdir -p dist/fonts
    rsync -a static/ dist/
    cat \
        node_modules/chiplib/libopenmpt.js crlf \
        node_modules/jquery/dist/jquery.min.js crlf \
        > dist/deps.js
    rsync -a tunes/files/ dist/tunes/
    cp fonts/chintzy.ttf dist/fonts
    ttf2woff fonts/chintzy.ttf dist/fonts/chintzy.woff
    ttf2eot fonts/chintzy.ttf dist/fonts/chintzy.eot
    gulp --production
    cd dist
    cat deps.js ../crlf client.js > js.js
    rm deps.js client.js
    rm -f ../crlf
}

main "$@"
