#!/bin/bash -e

root=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
pack="http://pub.keygenmusic.org/music%20pack/2017/2017-04/2017-04-pack.7z"

main() {
    cd "$root"
    [[ -f pack.7z ]] || wget "$pack" -O pack.7z
    rm -fr tmp-tunes tunes
    mkdir -p tmp-tunes tunes/files
    (cd tmp-tunes; 7za x ../pack.7z)

    ./scripts/package.py tmp-tunes tunes/files tunes/data.json
    rm -fr tmp-tunes
}

main
